places = ['prague', 'amsterdam', 'new york', 'dubai', 'hong kong']
print(f"Original List")
print(places)
print(f"\nSorted List")
print(sorted(places))
print(f"\nOriginal List")
print(places)
print(f"\nReversed List")
print(sorted(places, reverse=True))
print(f"\nOriginal List")
print(places)
places.reverse()
print(f"\nReversed List")
print(places)
places.reverse()
print(f"\nOriginal List")
print(places)
places.sort()
print(f"\nSorted List")
print(places)
places.sort(reverse=True)
print(f"\nReversed List")
print(places)


